Gpstel/Models/CHIP.cs
namespace Gpstel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Data.Entity;
    using System.Linq;

    [Table("CHIP")]
    public partial class CHIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHIP()
        {
            GPS = new HashSet<GPS>();
        }

        [Key]
        public int idchip { get; set; }

        [StringLength(50)]
        public string operador { get; set; }

        [StringLength(20)]
        public string tipo_contrato { get; set; }

        [StringLength(18)]
        public string numero { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPS> GPS { get; set; }
        public void guardarEditar()
        {

            try
            {
                using (var context = new ModelGps())
                {
                    if (this.idchip == 0)
                    {
                        context.Entry(this).State = EntityState.Added;
                    }
                    else
                    {
                        context.Entry(this).State = EntityState.Modified;
                    }
                    context.SaveChanges();
                }
            }
            catch (Exception)
            {

                throw;
            }

        }

        public List<CHIP> listarchip()
        {

            var listaChips = new List<CHIP>();

            try
            {
                using (var context = new ModelGps())
                {
                    listaChips = context.CHIP.ToList();
                }
            }
            catch (Exception e)
            {

                throw new Exception(e.Message);
            }
            return listaChips;
        }

        public CHIP obtenerChip(int id)
        {
            var objChip = new CHIP();

            try
            {
                using (var context = new ModelGps())
                {

                    objChip = context.CHIP
                        .Include("GPS")
                        .Where(x => x.idchip == id)
                        .Single();

                }

            }
            catch (Exception e)
            {

                throw new Exception(e.Message);
            }
            return objChip;

        }

        public void eliminarChip()
        {

            try
            {
                using (var context = new ModelGps())
                {
                    context.Entry(this).State = EntityState.Deleted;


                    context.SaveChanges();
                }
            }
            catch (Exception e)
            {

                throw new Exception(e.Message);
            }
        }

        public List<CHIP> obtenerChipnoRepetido()
        {

            var noRepetido = new List<CHIP>();
            try
            {

                using (var context = new ModelGps())
                {



                    //  noRepetido = context.CHIP.SqlQuery("Select * from CHIP where not exists (select null from GPS where GPS.idchip = CHIP.idchip)")
                    //    .ToList();


                    noRepetido = context.Database.SqlQuery<CHIP>("Select * from CHIP where not exists (select null from GPS where GPS.idchip = CHIP.idchip)")
                   .ToList();


                }
            }
            catch (Exception)
            {

                throw;
            }
            return noRepetido;
        }
    
}
}

Gpstel/Controllers/ChipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Gpstel.Models;
using Gpstel.Security;

namespace Gpstel.Controllers
{
    public class ChipController : Controller
    {
        private BaseRespuesta resultado = new BaseRespuesta();
        JavaScriptSerializer serializer = new JavaScriptSerializer();
        private CHIP objChip = new CHIP();

        // GET: Chip
        [CustomAuthorize(Roles = "admin")]
        public ActionResult Index()
        {


            return View(objChip.listarchip());
        }
        [HttpPost]
        public ActionResult guardarEditar(CHIP chip) {

            var resultado = new BaseRespuesta();

            try
            {
                chip.guardarEditar();

                resultado.mensaje = "Exito en el Proceso";
                resultado.ok = "tru";
            }
            catch (Exception e)
            {
                resultado.mensaje = e.Message;
                resultado.ok = "false";

            }

            return Json(resultado);

        }
        [HttpPost]
        public JsonResult getChip(int id)
        {
            var chip = new CHIP();
            chip = objChip.obtenerChip(id);
            chip.GPS=null;

            return Json(chip);
        }

        
        public ActionResult eliminarChip(int id) {

            try
            {
                objChip.idchip = id;
                objChip.eliminarChip();
            }
            catch (Exception)
            {

                return Redirect("~/Chip");
            }



            return Redirect("~/Chip");
        }
    }
}

Gpstel/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gpstel.Models;
using Gpstel.Security;

namespace Gpstel.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        ModelGps context = null;
        [CustomAuthorize(Roles = "admin,employee")]
        public ActionResult Index()
        {
            context = new ModelGps();
            return View(context.Vehiculo.ToList());
        }
        public ActionResult Detalle(int id) {
            context = new ModelGps();
            ViewBag.idVehiculo = id;
            return PartialView(context.Pago.Where(x=>x.idvehiculo==id).OrderByDescending(x=>x.fecha_pago).ToList());
        }
        [CustomAuthorize(Roles = "admin,employee")]
        public ActionResult Index2(string operador) {
            context = new ModelGps();
            if (operador == null)
            {
                ViewBag.operadorreporte = operador;
                return View(context.CHIP.ToList());
            }
            else
            {
                //context = new ModelGps();
                ViewBag.operadorreporte = operador;
                return View(context.CHIP.Where(x => x.operador == operador).ToList());
            }

            
        }
        [CustomAuthorize(Roles = "admin,employee")]
        public ActionResult Index3() {
           
            
            return View();
        }
        //public ActionResult Chip(string operador) {
            
        //}
    }
}

Gpstel/Views/Reporte/Chip.cshtml
@model List<Gpstel.Models.CHIP>

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>

                <th>Concepto</th>
                <th>Fecha</th>
                <th>Monto</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>@item.numero</td>
                    <td>@item.tipo_contrato</td>
                    <td>@item.operador</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Gpstel/Views/Reporte/Detalle.cshtml
@model List<Gpstel.Models.Pago>

@{

    Gpstel.Models.Vehiculo vehiculo = new Gpstel.Models.Vehiculo();
    var mivehiculo = vehiculo.obtenerVehiculoxId(Convert.ToInt32(ViewBag.idVehiculo));
}


<div id="imprimir">
    <div class="container dt-body-center">
        <div class="panel panel-default">
            <div class="panel panel-heading">
                <h2 style="vertical-align:middle">Datos del Vehiculo </h2>
            </div>
            <div id="contenido">
                <div class="container">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col">
                                <label>Placa</label>
                                <label class="form-control">@mivehiculo.placa</label>
                            </div>
                            <div class="col">
                                <label>Año del Vehiculo</label>
                                <label class="form-control">@mivehiculo.anio_vehiculo</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label>NRO. de Motor</label>
                                <label class="form-control">@mivehiculo.nro_motor</label>
                            </div>
                            <div class="col">
                                <label>Particular/MTC</label>
                                <label class="form-control">@mivehiculo.particular_mtc</label>
                            </div>
                        </div>
                        @{ DateTime date = new DateTime();
                            date = Convert.ToDateTime(mivehiculo.fecha_instalacion);
                        }
                        <div class="row">
                            <div class="col">
                                <label>Fecha de Instalacion</label>
                                <label class="form-control">@date.Day/@date.Month/@date.Year</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h2>Lista de Pagos por Vehiculo</h2>
  
        <table class="table table-striped">
            <thead>
                <tr>

                    <th>Concepto</th>
                    <th>Fecha</th>
                    <th>Monto</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>

                        <td>@item.concepto</td>
                        <td>@item.fecha_pago</td>
                        <td>@item.monto</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
<div class="dt-center">
    <a href="javascript:pruebaDivAPdf()" class="btn btn-info">Pasar a PDF</a>
</div>
<script>
    function pruebaDivAPdf() {
        var pdf = new jsPDF('p', 'pt', 'letter');
        source = $('#imprimir')[0];

        specialElementHandlers = {
            '#bypassme': function (element, renderer) {
                return true
            }
        };
        margins = {
            top: 80,
            bottom: 60,
            left: 40,
            width: 522
        };

        pdf.fromHTML(
            source,
            margins.left, // x coord
            margins.top, { // y coord
                'width': margins.width,
                'elementHandlers': specialElementHandlers
            },

            function (dispose) {
                pdf.save('Reporte.pdf');
            }, margins
        );
    }
</script>

Gpstel/Views/Reporte/Index.cshtml
@model List<Gpstel.Models.Vehiculo>
@{
    ViewBag.Title = "Index";
}

<h2>Lista de Vehiculos</h2>
<table class="table">
    <thead>
        <tr>
            <th>Placa</th>
            <th>Modelo</th>
            <th>Motor</th>
            <th>Opcion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.placa</td>
                <td>@item.modelo</td>
                <td>@item.nro_motor</td>
                <td>@Ajax.ActionLink("Ver Datos","Detalle","Reporte",new {id = item.idvehiculo},new AjaxOptions { HttpMethod="GET", InsertionMode=InsertionMode.Replace, UpdateTargetId="detalle"}, new { @class="btn btn-info"})</td>
            </tr>
        }
    </tbody>
</table>
<div id="detalle"></div>

Gpstel/Views/Reporte/Index2.cshtml
@model List<Gpstel.Models.CHIP>
@{
    var operadorreporte=ViewBag.operadorreporte;
}
<h1>Seleccione Operador de Telefonia</h1>
@using (Html.BeginForm("Index2", "Reporte", FormMethod.Post, new AjaxOptions{ HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "detalle"}))
{
    <span>Operador:</span> @*@Html.TextBox("operador")*@
    <select name="operador" id="operador">
        <option value="movistar">Movistar</option>
        <option value="bitel">Bitel</option>
        <option value="entel">Entel</option>
        <option value="claro">Claro</option>
    </select>
    <input type="submit" value="Buscar" />        
}
@if (operadorreporte != null)
{
    <div id="imprimir">
        <h2>Reporte de Chip @operadorreporte</h2>
        <div id="detalle">
        
                <table class="table table-striped">
                    <thead>
                        <tr>

                            <th>Numero</th>
                            <th>Tipo de Contrato</th>
                            <th>Operador</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>@item.numero</td>
                                <td>@item.tipo_contrato</td>
                                <td>@item.operador</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
  
    <br />
    <div class="dt-center">
        <center>
            <a href="javascript:pruebaDivAPdf()" class="btn btn-info">Pasar a PDF</a>
        </center>
    </div>
}

<script>
    function pruebaDivAPdf() {
        var pdf = new jsPDF('p', 'pt', 'letter');
        source = $('#imprimir')[0];

        specialElementHandlers = {
            '#bypassme': function (element, renderer) {
                return true
            }
        };
        margins = {
            top: 80,
            bottom: 60,
            left: 40,
            width: 522
        };

        pdf.fromHTML(
            source,
            margins.left, // x coord
            margins.top, { // y coord
                'width': margins.width,
                'elementHandlers': specialElementHandlers
            },

            function (dispose) {
                pdf.save('Reporte.pdf');
            }, margins
        );
    }
</script>

Gpstel/Views/Reporte/Index3.cshtml
@using Gpstel.Models;
@{
    var context = new ModelGps();
    var chipsporvehiculo = context.Database.SqlQuery<Vehiculo>("select * from Vehiculo join GPS on Vehiculo.idgps = GPS.idgps join CHIP on CHIP.idchip = GPS.idchip ")
                   .ToList();
    GPS gpsporvehiculo = new GPS();
    var chipporvehiculo = context.Database.SqlQuery<CHIP>("Select * from CHIP where not exists (select null from GPS where GPS.idchip = CHIP.idchip)");
}



    <div id="imprimir">
        <div class="container">
            <h1>Chips Usador por Vehiculos</h1>

            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>Placa</th>
                        <th>imei</th>
                        <th>numero</th>
                        <th>operador</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in chipsporvehiculo)
                    {
                        var item2 = gpsporvehiculo.obtenerGps(Convert.ToInt32(item.idgps));
                        <tr>

                            <td>@item.placa</td>
                            <td>@item2.imei</td>
                            <td>@item2.CHIP.numero</td>
                            <td>@item2.CHIP.operador</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="container">
            <h1>Chips sin usar</h1>
            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>Numero</th>
                        <th>Tipo de Contrato</th>
                        <th>Operador</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in chipporvehiculo)
                    {
                        <tr>

                            <td>@item.numero</td>
                            <td>@item.tipo_contrato</td>
                            <td>@item.operador</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>

        <br />
        <div class="dt-center">
            <center>
                <a href="javascript:pruebaDivAPdf()" class="btn btn-info">Pasar a PDF</a>
            </center>
        </div>

<script>
    function pruebaDivAPdf() {
        var pdf = new jsPDF('p', 'pt', 'letter');
        source = $('#imprimir')[0];

        specialElementHandlers = {
            '#bypassme': function (element, renderer) {
                return true
            }
        };
        margins = {
            top: 80,
            bottom: 60,
            left: 40,
            width: 522
        };

        pdf.fromHTML(
            source,
            margins.left, // x coord
            margins.top, { // y coord
                'width': margins.width,
                'elementHandlers': specialElementHandlers
            },

            function (dispose) {
                pdf.save('Reporte.pdf');
            }, margins
        );
    }
</script>